# Generated by Django 5.2.6 on 2025-09-26 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name_plural": "Order"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name_plural": "Product"},
        ),
    ]
